Enable and disable tracing
vrajat/yugabyte-db pull request #31
Opened 2023-03-29 11:53 UTC by abhinab-yb

2023-03-30 10:57 UTC, vrajat reviewed
Please add `isYugabyteDbEnabled()` in critical code paths like postgres.c

2023-04-03 09:05 UTC, vrajat requested changes
Can you add tests for:
* `query_id` or `pid` not specified
* Accept NULL instead of -1 for pid. NULL -> current session.  `select is_yb_pg_enable_tracing(pid => (select pg_backend_pid())` should return true

2023-04-03 09:12 UTC, vrajat commented
Also can break the test file into sections  and add comments to describe the section? For example a section to test default for pid.

2023-04-04 05:16 UTC, vrajat requested changes
LGTM. Minor comments.

One test is required that will create multiple connections and run tests. Your call if you want to add it now or create an issue in this project or in a spreadsheet or notes doc so that we dont lose track.

2023-04-04 05:16 UTC, vrajat commented on src/postgres/src/backend/storage/lmgr/proc.c
> +		procs[i].maxQueries = 10;
Ditto. Pick this from a GUC or from a global constant.

2023-04-04 05:16 UTC, vrajat commented on src/postgres/src/backend/tcop/postgres.c
> +			YBCStartQueryEvent("analyz_and_rewrite");
Nit: Can you fix the typo I introduced ? `analyze_and_rewrite`.

2023-04-04 05:16 UTC, vrajat commented on src/postgres/src/backend/tcop/postgres.c
> +			YBCStopQueryEvent("analyz_and_rewrite");
Same: Typo

2023-04-04 05:16 UTC, vrajat commented on src/postgres/src/test/regress/sql/yb_pg_tracing.sql
> +SELECT is_yb_pg_tracing_enabled(pid => 0, query_id => NULL);
In this case, should `is_yb_pg_tracing_enabled()` also return true as it is checking for this session?

2023-04-04 05:16 UTC, vrajat commented on src/postgres/src/test/regress/sql/yb_pg_tracing.sql
> +SELECT yb_pg_enable_tracing(query_id => 12345);
Nit: Add a comment that a warning is expected.

2023-04-04 05:16 UTC, vrajat commented on src/postgres/src/test/regress/sql/yb_pg_tracing.sql
> +SELECT yb_pg_disable_tracing(query_id => 12346789);
Add a comment that this will throw a warning.

2023-04-04 05:16 UTC, vrajat commented on src/yb/yql/pggate/pg_session.h
> +  std::string trace_file_name_base_ = "/home/asaha/var/logs/tserver/";
Can you test if `trace_file_name_base_` can be replaced with `FLAG_logs_dir`?

2023-04-04 06:33 UTC, abhinab-yb commented on src/postgres/src/test/regress/sql/yb_pg_tracing.sql
> +SELECT is_yb_pg_tracing_enabled(pid => 0, query_id => NULL);
its checking for all the sessions as `pid = 0`, so it should return `true`

2023-04-04 08:30 UTC, vrajat approved these changes

2023-04-04 08:42 UTC, merged